// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:date/secrets.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: Secrets.API_KEY_1,
    appId: '1:23261519945:web:cdddbdfe77460d20c9df98',
    messagingSenderId: '23261519945',
    projectId: 'dating-87c75',
    authDomain: 'dating-87c75.firebaseapp.com',
    storageBucket: 'dating-87c75.appspot.com',
    measurementId: 'G-E30RGSM76Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: Secrets.API_KEY_2,
    appId: '1:23261519945:android:cb20ee35211ca140c9df98',
    messagingSenderId: '23261519945',
    projectId: 'dating-87c75',
    storageBucket: 'dating-87c75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: Secrets.API_KEY_3,
    appId: '1:23261519945:ios:2154765e88cf0fdec9df98',
    messagingSenderId: '23261519945',
    projectId: 'dating-87c75',
    storageBucket: 'dating-87c75.appspot.com',
    iosClientId:
        '23261519945-0o88uqio0727fh3knpqvkomeihsuq0rp.apps.googleusercontent.com',
    iosBundleId: 'com.example.date',
  );
}
